// SAT Configuration
export const SAT_CONFIG = {
  name: "SAT",
  sections: {
    reading_writing: { name: "Reading & Writing", min: 200, max: 800 },
    math: { name: "Math", min: 200, max: 800 },
  },
  total: { min: 400, max: 1600 },
  weakAreas: [
    "Algebra",
    "Advanced Math",
    "Problem Solving & Data Analysis",
    "Geometry & Trigonometry",
    "Grammar & Syntax",
    "Reading Comprehension",
    "Vocabulary in Context",
    "Time Management",
  ],
};

// ACT Configuration
export const ACT_CONFIG = {
  name: "ACT",
  sections: {
    english: { name: "English", min: 1, max: 36 },
    math: { name: "Math", min: 1, max: 36 },
    reading: { name: "Reading", min: 1, max: 36 },
    science: { name: "Science", min: 1, max: 36 },
    writing: { name: "Writing (Optional)", min: 1, max: 36 },
  },
  total: { min: 1, max: 36 },
  weakAreas: [
    "Grammar & Punctuation",
    "Algebra",
    "Geometry",
    "Trigonometry",
    "Reading Speed",
    "Science Data Interpretation",
    "Experimental Design",
    "Time Management",
    "Test Endurance",
  ],
};

// AP Exam Categories and Subjects
export const AP_CATEGORIES = [
  {
    name: "Math and Computer Science",
    exams: [
      { id: "calc-ab", name: "AP Calculus AB" },
      { id: "calc-bc", name: "AP Calculus BC" },
      { id: "stats", name: "AP Statistics" },
      { id: "precalc", name: "AP Precalculus" },
      { id: "csa", name: "AP Computer Science A" },
      { id: "csp", name: "AP Computer Science Principles" },
    ],
  },
  {
    name: "Sciences",
    exams: [
      { id: "bio", name: "AP Biology" },
      { id: "chem", name: "AP Chemistry" },
      { id: "env-sci", name: "AP Environmental Science" },
      { id: "phys1", name: "AP Physics 1" },
      { id: "phys2", name: "AP Physics 2" },
      { id: "phys-c-mech", name: "AP Physics C: Mechanics" },
      { id: "phys-c-emag", name: "AP Physics C: Electricity & Magnetism" },
    ],
  },
  {
    name: "English",
    exams: [
      { id: "lang", name: "AP English Language and Composition" },
      { id: "lit", name: "AP English Literature and Composition" },
    ],
  },
  {
    name: "History and Social Sciences",
    exams: [
      { id: "us-hist", name: "AP United States History" },
      { id: "world-hist", name: "AP World History: Modern" },
      { id: "euro-hist", name: "AP European History" },
      { id: "gov", name: "AP US Government and Politics" },
      { id: "comp-gov", name: "AP Comparative Government and Politics" },
      { id: "macro", name: "AP Macroeconomics" },
      { id: "micro", name: "AP Microeconomics" },
      { id: "psych", name: "AP Psychology" },
      { id: "human-geo", name: "AP Human Geography" },
    ],
  },
  {
    name: "World Languages",
    exams: [
      { id: "spanish-lang", name: "AP Spanish Language and Culture" },
      { id: "spanish-lit", name: "AP Spanish Literature and Culture" },
      { id: "french", name: "AP French Language and Culture" },
      { id: "german", name: "AP German Language and Culture" },
      { id: "chinese", name: "AP Chinese Language and Culture" },
      { id: "japanese", name: "AP Japanese Language and Culture" },
      { id: "italian", name: "AP Italian Language and Culture" },
      { id: "latin", name: "AP Latin" },
    ],
  },
  {
    name: "Arts",
    exams: [
      { id: "art-hist", name: "AP Art History" },
      { id: "music-theory", name: "AP Music Theory" },
      { id: "art-2d", name: "AP 2-D Art and Design" },
      { id: "art-3d", name: "AP 3-D Art and Design" },
      { id: "art-drawing", name: "AP Drawing" },
    ],
  },
  {
    name: "AP Capstone",
    exams: [
      { id: "seminar", name: "AP Seminar" },
      { id: "research", name: "AP Research" },
    ],
  },
];

// AP Weak Areas by Subject
export const AP_WEAK_AREAS: Record<string, string[]> = {
  "calc-ab": [
    "Limits",
    "Derivatives",
    "Applications of Derivatives",
    "Integrals",
    "Applications of Integrals",
    "Differential Equations",
    "FRQ Strategy",
    "Calculator Use",
    "Time Management",
  ],
  "calc-bc": [
    "Limits",
    "Derivatives",
    "Applications of Derivatives",
    "Integrals",
    "Applications of Integrals",
    "Differential Equations",
    "Sequences and Series",
    "FRQ Strategy",
    "Calculator Use",
    "Time Management",
  ],
  stats: [
    "Probability",
    "Distributions",
    "Hypothesis Testing",
    "Confidence Intervals",
    "Chi-Square Tests",
    "Linear Regression",
    "Experimental Design",
    "FRQ Writing",
  ],
  precalc: [
    "Functions & Transformations",
    "Polynomial Functions",
    "Rational Functions",
    "Exponential & Logarithmic",
    "Trigonometric Functions",
    "Sequences & Series",
    "Parametric Equations",
  ],
  csa: [
    "Classes & Objects",
    "Arrays & Lists",
    "Inheritance & Polymorphism",
    "Recursion",
    "Sorting & Searching",
    "2D Arrays",
    "String Methods",
    "File I/O",
  ],
  csp: [
    "Programming Concepts",
    "Algorithms",
    "Data Representation",
    "Internet & Networks",
    "Cybersecurity",
    "Global Impact",
    "Create Task",
  ],
  bio: [
    "Cell Structure",
    "Cellular Energetics",
    "Genetics",
    "Evolution",
    "Ecology",
    "Data Analysis",
    "Experimental Design",
    "FRQ Writing",
  ],
  chem: [
    "Atomic Structure",
    "Chemical Bonding",
    "Stoichiometry",
    "Thermodynamics",
    "Equilibrium",
    "Acids & Bases",
    "Kinetics",
    "Electrochemistry",
    "FRQ Calculations",
  ],
  "env-sci": [
    "Earth's Systems",
    "Biomes & Ecology",
    "Population Dynamics",
    "Land & Water Use",
    "Energy Resources",
    "Pollution & Climate",
    "Sustainability",
  ],
  phys1: [
    "Kinematics",
    "Dynamics",
    "Energy",
    "Momentum",
    "Rotation",
    "Oscillations",
    "Waves",
    "Fluids",
    "Electrostatics",
  ],
  phys2: [
    "Thermodynamics",
    "Electric Fields",
    "Circuits",
    "Magnetism",
    "Electromagnetic Induction",
    "Optics",
    "Modern Physics",
  ],
  "phys-c-mech": [
    "Kinematics",
    "Newton's Laws",
    "Energy & Work",
    "Momentum",
    "Rotation",
    "Gravitation",
    "Oscillations",
  ],
  "phys-c-emag": [
    "Electrostatics",
    "Electric Fields",
    "Circuits",
    "Magnetism",
    "Magnetic Fields",
    "Electromagnetic Induction",
    "Maxwell's Equations",
  ],
  lang: [
    "Rhetorical Analysis",
    "Argument Essay",
    "Synthesis Essay",
    "Identifying Rhetoric",
    "Evidence Integration",
    "Timed Writing",
    "AP Exam Format",
  ],
  lit: [
    "Literary Analysis",
    "Essay Writing",
    "Characterization",
    "Symbolism & Themes",
    "Poetic Devices",
    "Timed Writing",
    "Text Selection",
  ],
  "us-hist": [
    "Periodization",
    "Cause & Effect",
    "DBQ (Document-Based Question)",
    "LEQ (Long Essay Question)",
    "SAQ (Short Answer Question)",
    "Evidence Selection",
    "Timeline Building",
  ],
  "world-hist": [
    "Periodization",
    "Comparisons",
    "Causation",
    "DBQ Writing",
    "LEQ Writing",
    "SAQ Quick Answers",
    "Global Themes",
  ],
  "euro-hist": [
    "Periods & Movements",
    "Key Events",
    "Causation Analysis",
    "DBQ Strategy",
    "LEQ Organization",
    "Document Analysis",
    "Comparative Essays",
  ],
  gov: [
    "Constitutional Foundations",
    "Congress",
    "Executive Branch",
    "Judicial System",
    "Civil Rights",
    "Political Behavior",
    "Policy Analysis",
  ],
  "comp-gov": [
    "Comparative Systems",
    "UK System",
    "China's Government",
    "Russia's System",
    "Iran's System",
    "Mexico's System",
    "Policy Comparison",
  ],
  macro: [
    "Supply & Demand",
    "Production & Costs",
    "Perfect Competition",
    "Imperfect Competition",
    "Factor Markets",
    "Macro Measures",
    "Fiscal & Monetary Policy",
  ],
  micro: [
    "Supply & Demand",
    "Elasticity",
    "Consumer Behavior",
    "Production & Costs",
    "Perfect Competition",
    "Imperfect Competition",
    "Factor Markets",
  ],
  psych: [
    "Scientific Foundations",
    "Biopsychology",
    "Sensation & Perception",
    "Learning & Conditioning",
    "Motivation & Emotion",
    "Cognition",
    "Individual Differences",
  ],
  "human-geo": [
    "Maps & Spatial Data",
    "Population",
    "Cultural Patterns",
    "Political Geography",
    "Agriculture & Food",
    "Industrialization",
    "Urban Patterns",
    "Development",
  ],
  "spanish-lang": [
    "Listening Comprehension",
    "Reading Comprehension",
    "Speaking Skills",
    "Writing Skills",
    "Interpersonal Communication",
    "Presentational Speaking",
    "Presentational Writing",
  ],
  "spanish-lit": [
    "Literary Analysis",
    "Cultural Context",
    "Poetic Elements",
    "Prose Analysis",
    "Drama Analysis",
    "Essay Writing",
  ],
  french: [
    "Listening Comprehension",
    "Reading Comprehension",
    "Speaking Skills",
    "Writing Skills",
    "Interpersonal Communication",
    "Presentational Speaking",
  ],
  german: [
    "Listening Comprehension",
    "Reading Comprehension",
    "Speaking Skills",
    "Writing Skills",
    "Grammar Precision",
    "Verb Conjugations",
  ],
  chinese: [
    "Listening Comprehension",
    "Reading Comprehension",
    "Speaking Skills",
    "Writing Skills",
    "Character Recognition",
    "Pinyin Accuracy",
  ],
  japanese: [
    "Listening Comprehension",
    "Reading Comprehension (Kanji, Hiragana, Katakana)",
    "Speaking Skills",
    "Writing Skills",
    "Honorifics & Politeness",
    "Grammar Patterns",
  ],
  italian: [
    "Listening Comprehension",
    "Reading Comprehension",
    "Speaking Skills",
    "Writing Skills",
    "Verb Conjugations",
    "Sentence Construction",
  ],
  latin: [
    "Translation",
    "Grammar (Cases, Tenses)",
    "Vocabulary",
    "Roman Culture",
    "Prose Passages",
    "Poetic Analysis",
  ],
  "art-hist": [
    "Art Periods & Movements",
    "Artist Identification",
    "Contextual Analysis",
    "Formal Analysis",
    "Cultural Significance",
    "Comparative Analysis",
  ],
  "music-theory": [
    "Notation Reading",
    "Scales & Chords",
    "Voice Leading",
    "Part Writing",
    "Harmonic Analysis",
    "Form & Structure",
    "Listening Skills",
  ],
  "art-2d": [
    "Design Principles",
    "Color Theory",
    "Composition",
    "Medium Mastery",
    "Portfolio Development",
    "Concentration Piece",
  ],
  "art-3d": [
    "3D Design Principles",
    "Form & Space",
    "Material Understanding",
    "Structural Integrity",
    "Portfolio Development",
    "Concentration Piece",
  ],
  "art-drawing": [
    "Observational Skills",
    "Line & Form",
    "Value & Shading",
    "Perspective",
    "Composition",
    "Portfolio Consistency",
  ],
  seminar: [
    "Question Development",
    "Research Methods",
    "Argument Construction",
    "Evidence Evaluation",
    "Team Collaboration",
    "Presentation Skills",
  ],
  research: [
    "Research Question",
    "Research Design",
    "Data Collection",
    "Analysis Methods",
    "Report Writing",
    "Presentation",
  ],
};
